name: Docker Build
on:
  push:
    branches: [ master, develop ]

jobs:
  build-docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and push image
      run: |
          DOCKER_NAME=SnakeServerApi
          DOCKER_IMAGE=ghcr.io/miki669/SnakeServerApi/$DOCKER_NAME:${{ github.ref_name }}
          docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          docker build -f SnakeServer/Dockerfile --pull -t $DOCKER_IMAGE .
          docker push $DOCKER_IMAGE
