name: docker_image
on:
  push:
    branches: [ master, develop ]

jobs:
  build-docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build and push image
      run: |
          DOCKER_NAME=snake-server-api
          DOCKER_IMAGE=ghcr.io/miki669/snakeserverapi/$DOCKER_NAME:${{ github.ref_name }}
          docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          docker build -f snakesserverapi/Dockerfile --pull -t $DOCKER_IMAGE .
          docker push $DOCKER_IMAGE
